### ISSUE TITLE
Avahi Support

### ISSUE THREAD

**Issue by cyphar** [yast/yast-printer#11]
As far as I can tell, the YaST printer module doesn't support automatic discovery of printers through Avahi (which uses mDNS and other similar protocols). Is this on the TODO list? The current method of "just use `nmap` to find your printers" is quite annoying IMO.

Since `avahi-daemon` [has a DBus interface](http://avahi.org/wiki/ProgrammingDocs), it should be possible to hook into that to just get the IP address and other connection information and then use the setup tools already available in YaST. It's also possible to use `libavahi-core`, but that probably would require a lot more work.

I found [this](https://github.com/mvidner/ruby-dbus) DBus binding library for Ruby. We could probably take a look at how `avahi-browse` and similar official Avahi clients are implemented (or we could just wrap them).

**Comment by ancorgs** [comment]
I found this issue only 5 years after it was entered. :-/

Needless to say, active development of YaST Printer fully stopped years ago. Currently the YaST Team only performs the essential maintenance work needed to keep it working to a reasonable extent.

So I'm closing this issue. If someday YaST Printer gets a new developer, it may be reopened.
