### ISSUE TITLE
Request for redesign the printer configuration in yast

### ISSUE THREAD

**Issue by Mannshoch** [yast/yast-printer#41]
I'd not like how Printers are configured I created a Mockup that addresses some concerns.

- Chose the right paper, there are Paper sizes that are missing for Printing to PDF.
Depending on the Printer you are having Problems finding the correct size in a huge list of paper.
- Remove settings or preset settings on Printers.
![Main](https://user-images.githubusercontent.com/7795891/185046652-7022b6ec-02da-4894-95ae-7f9a537492b7.jpg)
![Paper-Screen](https://user-images.githubusercontent.com/7795891/185046671-ba05b3b0-749b-4259-a90d-783fa8c471e8.jpg)
![Output Device](https://user-images.githubusercontent.com/7795891/185046691-3c8b98cc-b71c-4936-b192-c75d8f620956.jpg)

**Comment by dgdavid** [comment]
Hi @Mannshoch!

Thank you so much for taking your time to fill in a request! Much appreciated.

However, we do not plan to enhance nor even continue developing this quite old YaST module, which is almost unmaintained. Maybe we should improve the README to put it clear there.

Sorry, hope you don't get too much disappointed.

Regards.

**Comment by shundhammer** [comment]
@Mannshoch : To clarify this further: That whole yast-printer module has been very much abandoned for a number of years. Even the original author and (still) maintainer made several attempts to drop it officially, but each of them was denied.

The reasoning for dropping was that all the modern desktops like KDE Plasma, GNOME, Xfce come with printer configuration modules or applets that are integrated much better into the desktop environment, and there are tools like CUPS etc. that do that better, and that are actively maintained.

We are really sorry to have to disappoint you here. You gave a lot of thought to this, and we greatly appreciate that.

**Comment by Mannshoch** [comment]
Then please remove Printer from the Yast!
Other wise, do it better than CUPS! 

I see many Times Problems with the Paper management because I permanently have to search my Paper sizes I use and struggle manytiems with the Border and others like print to PDF.

Simply close is not a valid solution.

**Comment by shundhammer** [comment]
> Then please remove Printer from the Yast!

That was exactly what those drop requests by the author / maintainer were all about.


> I see many Times Problems with the Paper management because I permanently have to search my Paper sizes I use and struggle many times with the Border and others like print to PDF.

Did you try using your desktop's printer applet?

**Comment by Mannshoch** [comment]
I worked with CUPS for that. In my opinion it's more a Workaround than a solution. I'm able to work as I please. I do not like the CUPS Website. The Gnome Desktop Printer settings are reduced. Papersettings are not possible. 
I have to say, the Problems on Windows are the same. Printing A0 or A2 Paperformat to PDF seems more a pain in the ass.

**Comment by Mannshoch** [comment]
I would like to say that I find Yast to be a tool that says, 
"We collect the scattered options of different programs and provide a tool to set them together correctly and clearly."
Currently I find that Yast is no longer able to do this. Gnome and KDE have learned a lot and are currently better in some places. But unfortunately they don't think outside the box either. 

Let's take the example of printers. CUPS has stopped in the development, Gnome and KDE only care about the simple usage. But nowadays, in the paperless office, if a physical output is needed, more is required. (Even the printer manufacturers have not yet understood this).
It is not only about the plain stationery. It's about PDFs for tablets and cell phones generated from Impress, Gimp or Abiword. It's about presentations with a projector or video conferences where you need a diagonal screen, but in 4K resolution. 
While we are at printing, it should be as borderless as possible for photos, in A0 format just for PDF display or in CYMK format needed.
Sometimes only with a small margin, because you don't need to put anything in a physical file folder anyway and just need a pleasant display. 

Yast should therefore make it possible to define the paper and screen formats used in everyday life.
From connected printers minimum margins to recognize (at most photo printing options to include let) and configure this information into the templates and print settings of the most frequently used programs. Preferably with the possibility to define a corporate identity, such as the font to be used or how multi-page documents are numbered and if necessary certain paper trays, because there is high-quality paper or one with pre-printed information.

In the end, it's not the printer that interests me when it comes to printing, but the format. This is also something I don't understand, the printer is of no interest in everyday life. It is the format that interests me, and in the end the information about where to pick up the printout.
I would be very happy if Yast could take on a pioneering role here again.
